services:
  backend:
    build: ./backend
    container_name: barbearia_backend
    restart: on-failure
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    env_file: ./backend/.env
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: barbearia_mysql
    restart: on-failure
    ports:
      - "3306:3306"
    env_file: ./backend/.env
    volumes:
      - barbearia_mysql_data:/var/lib/mysql

volumes:
  barbearia_mysql_data: